rg_name         = "TestRG"
location        = "eastus"
environment     = "Production"
owner           = "Omkar"
project_name    = "Testing"
billing_level   = "RG"
billing_contact = "Omkar Jamdade"
cost_center     = "Pune-IT-SHS"